### ISSUE TITLE
Bad name for a variable

### ISSUE THREAD

**Issue by eg9** [cfiandra/timeline#3]
In the `\timeline` command, `\xi` is used as a variable for `\foreach`, but this obviously has side effects if the user wants to typeset a xi in the nodes.

https://tex.stackexchange.com/q/476089/4427

**Comment by cfiandra** [comment]
Fixed in commit [fix-conflict-xi ](https://github.com/cfiandra/timeline/commit/92c51b587ab82efa395cd25ceb37bdbd64449f68).
